# Please keep AllCops, Bundler, Layout, Style, Metrics groups and then order cops
# alphabetically
#
# References:
#   * https://github.com/bbatsov/ruby-style-guide
#   * https://rubocop.readthedocs.io/

require: rubocop-rails

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
<<<<<<< HEAD
  TargetRubyVersion: 2.5

  
=======
  TargetRubyVersion: 2.5
>>>>>>> 3e61dbe26a8e71d1481872f13e7fc6702703ee41
