inherit_from: .rubocop_todo.yml

# Please keep AllCops, Bundler, Layout, Style, Metrics groups and then order cops
# alphabetically
#
# References:
#   * https://github.com/bbatsov/ruby-style-guide
#   * https://rubocop.readthedocs.io/

require: rubocop-rails

Metrics/LineLength:
  Max: 130

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
  TargetRubyVersion: 2.5